/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.katakati;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author rionr
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */ 
    int count=0,p1rec=0,p2rec=0;
	 String b1,b2,b3,b4,b5,b6,b7,b8,b9,p1r,p2r,name1,name2;
    public main() {
        initComponents();
        name();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        player1name = new javax.swing.JLabel();
        player2name = new javax.swing.JLabel();
        player1rec = new javax.swing.JLabel();
        player2rec = new javax.swing.JLabel();
        btnreset = new javax.swing.JButton();
        reslvl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));

        btn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        player1name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        player2name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        player1rec.setBackground(new java.awt.Color(0, 204, 204));
        player1rec.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        player1rec.setForeground(new java.awt.Color(0, 204, 204));

        player2rec.setBackground(new java.awt.Color(51, 204, 0));
        player2rec.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        player2rec.setForeground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(player1name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player2name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(player1rec, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(player2rec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(player1rec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player1name, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player2name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2rec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnreset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        reslvl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("New Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reslvl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnreset, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(reslvl, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name()
    {
    
        
       name1= JOptionPane.showInputDialog("Input player 1 name");
       player1name.setText(name1);
       name2= JOptionPane.showInputDialog("Input player 2 name");
       player2name.setText(name2);
    
    }
    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        btn1.setText("");
        btn2.setText("");
        btn3.setText("");
        btn4.setText("");
        btn5.setText("");
        btn6.setText("");
        btn7.setText("");
        btn8.setText("");
        btn9.setText("");
        reslvl.setText("");
        b1=null;
        b2=null;
        b3=null;
        b4=null;
        b5=null;
        b6=null;
        b7=null;
        b8=null;
        b9=null;
        count=0;
        btn1.setBackground(new Color(240, 240, 240));
        btn2.setBackground(new Color(240, 240, 240));
        btn3.setBackground(new Color(240, 240, 240));
        btn4.setBackground(new Color(240, 240, 240));
        btn5.setBackground(new Color(240, 240, 240));
        btn6.setBackground(new Color(240, 240, 240));
        btn7.setBackground(new Color(240, 240, 240));
        btn8.setBackground(new Color(240, 240, 240));
        btn9.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_btnresetActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if("".equals(btn1.getText()))
        {

            if(count%2==0)

            {
                btn1.setText("X");
                b1="X";
            }

            else

            {
                btn1.setText("O");
                b1="O";
            }

            if((b1=="X" && b1==b2 && b2==b3))
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn1.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn2.setBackground(Color.CYAN);
                btn3.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            else if((b1=="X" && b1==b5 && b5==b9))
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn1.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn5.setBackground(Color.CYAN);
                btn9.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            else if((b1=="X" && b1==b4 && b4==b7))
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn1.setBackground(Color.CYAN);
                btn4.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn7.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            if(b1=="O" && b1==b2 && b2==b3)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn1.setBackground(Color.GREEN);
                btn2.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn3.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            else if((b1=="O" && b1==b5 && b5==b9))
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn1.setBackground(Color.GREEN);
                btn5.setBackground(Color.GREEN);
                btn9.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            else if((b1=="O" && b1==b4 && b4==b7))
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn1.setBackground(Color.GREEN);
                btn4.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn7.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            count++;
            if (count==9)
            {reslvl.setText("Game is Draw...");
            JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();}

        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if(btn2.getText()=="")
        {
            if(count%2==0)

            {
                btn2.setText("X");
                b2="X";
            }

            else

            {
                btn2.setText("O");
                b2="O";
            }

            if(b2=="X" && b1==b2 && b2==b3)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn2.setBackground(Color.CYAN);
                btn1.setBackground(Color.CYAN);
                btn3.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }
            else if(b2=="X" && b2==b5 && b5==b8)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn2.setBackground(Color.CYAN);
                btn5.setBackground(Color.CYAN);
                btn8.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            else if(b2=="O" && b1==b2 && b2==b3)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn2.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn1.setBackground(Color.GREEN);
                btn3.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }
            else if(b2=="O" && b2==b5 && b5==b8)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn2.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn5.setBackground(Color.GREEN);
                btn8.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            count++;
            if (count==9)
            {reslvl.setText("Game is Draw...");
            JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();}

        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if(btn3.getText()=="")
        {
            if(count%2==0)

            {
                btn3.setText("X");
                b3="X";
            }

            else

            {
                btn3.setText("O");
                b3="O";
            }

            if(b3=="X" && b3==b2 && b1==b3)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn1.setBackground(Color.CYAN);
                btn2.setBackground(Color.CYAN);
                btn3.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }
            else if(b3=="X" && b3==b5 && b5==b7)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn3.setBackground(Color.CYAN);
                btn5.setBackground(Color.CYAN);
                btn7.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
                
            }
            else if(b3=="X" && b3==b6 && b6==b9)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn3.setBackground(Color.CYAN);
                btn6.setBackground(Color.CYAN);
                btn9.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }
            else if(b3=="O" && b3==b2 && b1==b3)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn1.setBackground(Color.GREEN);
                btn2.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn3.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }
            else if(b3=="O" && b3==b5 && b5==b7)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn3.setBackground(Color.GREEN);
                btn5.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn7.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }
            else if(b3=="O" && b3==b6 && b6==b9)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn3.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn6.setBackground(Color.GREEN);
                btn9.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            count++;
            if (count==9)
            {reslvl.setText("Game is Draw...");
            JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();}

        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if(btn4.getText()=="")
        {
            if(count%2==0)

            {
                btn4.setText("X");
                b4="X";
            }

            else

            {
                btn4.setText("O");
                b4="O";
            }

            if(b4=="X" && b4==b5 && b5==b6)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn4.setBackground(Color.CYAN);
                btn5.setBackground(Color.CYAN);
                btn6.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();

            }
            else if(b4=="X" && b4==b1 && b4==b7)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn1.setBackground(Color.CYAN);
                btn4.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn7.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();

            }
            else if((b4=="O" && b4==b5 && b5==b6))
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn4.setBackground(Color.GREEN);
                btn5.setBackground(Color.GREEN);
                btn6.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }
            else if(b4=="O" && b4==b1 && b4==b7)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn4.setBackground(Color.GREEN);
                btn1.setBackground(Color.GREEN);
                btn7.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            count++;
            if (count==9)
            { reslvl.setText("Game is Draw...");
            JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();}
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if(btn5.getText()=="")
        {
            if(count%2==0)

            {
                btn5.setText("X");
                b5="X";
            }

            else

            {
                btn5.setText("O");
                b5="O";
            }

            if(b5=="X" && b4==b5 && b5==b6)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn4.setBackground(Color.CYAN);
                btn5.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn6.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();

            }

            else if(b5=="X" && b5==b2 && b5==b8)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn2.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn5.setBackground(Color.CYAN);
                btn8.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            else if(b5=="X" && b5==b1 && b5==b9)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn1.setBackground(Color.CYAN);
                btn5.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn9.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            else if(b5=="X" && b5==b3 && b5==b7)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn3.setBackground(Color.CYAN);
                btn5.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn7.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            else if(b5=="O" && b4==b5 && b5==b6)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn4.setBackground(Color.GREEN);
                btn5.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn6.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();

            }

            else if(b5=="O" && b5==b2 && b5==b8)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn2.setBackground(Color.GREEN);
                btn5.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn8.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            else if(b5=="O" && b5==b1 && b5==b9)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn1.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn5.setBackground(Color.GREEN);
                btn9.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            else if(b5=="O" && b5==b3 && b5==b7)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn3.setBackground(Color.GREEN);
                btn5.setBackground(Color.GREEN);
                btn7.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            count++;
            if (count==9)
            reslvl.setText("Game is Draw...");
            {JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();}
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if(btn6.getText()=="")
        {
            if(count%2==0)

            {
                btn6.setText("X");
                b6="X";
            }

            else

            {
                btn6.setText("O");
                b6="O";
            }

            if((b6=="X" && b4==b5 && b5==b6))
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn4.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn5.setBackground(Color.CYAN);
                btn6.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }
            else if(b6=="X" && b6==b3 && b6==b9)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn9.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn3.setBackground(Color.CYAN);
                btn6.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }
            else if(b6=="O" && b4==b5 && b5==b6)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn4.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn5.setBackground(Color.GREEN);
                btn6.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }
            else if(b6=="O" && b6==b3 && b6==b9)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn6.setBackground(Color.GREEN);
                btn9.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn3.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            count++;
            if (count==9)
            {reslvl.setText("Game is Draw...");
            JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();}
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if(btn7.getText()=="")
        {
            if(count%2==0)

            {
                btn7.setText("X");
                b7="X";
            }

            else

            {
                btn7.setText("O");
                b7="O";
            }

            if(b7=="X" && b7==b8 && b8==b9)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn8.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn9.setBackground(Color.CYAN);
                btn7.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();

            }
            else if(b7=="X" && b7==b4 && b4==b1)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn1.setBackground(Color.CYAN);
                btn4.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn7.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();

            }
            else if(b7=="X" && b7==b5 && b5==b3)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn3.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn5.setBackground(Color.CYAN);
                
                btn7.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();

            }
            else if((b7=="O" && b7==b8 && b8==b9) )
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn8.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn9.setBackground(Color.GREEN);
                btn7.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            else if(b7=="O" && b7==b4 && b4==b1)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn4.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn1.setBackground(Color.GREEN);
                btn7.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }
            else if(b7=="O" && b7==b5 && b5==b3)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn3.setBackground(Color.GREEN);
                btn5.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn7.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();

            }

            count++;
            if (count==9)
            {reslvl.setText("Game is Draw...");
            JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
        }}
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if(btn8.getText()=="")
        {
            if(count%2==0)

            {
                btn8.setText("X");
                b8="X";
            }

            else

            {
                btn8.setText("O");
                b8="O";
            }

            if(b8=="X" && b8==b5 && b5==b2)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn8.setBackground(Color.CYAN);
                btn5.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn2.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }
            else if(b8=="X" && b8==b7 && b8==b9)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn8.setBackground(Color.CYAN);
                btn7.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn9.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }
            else if(b8=="O" && b8==b5 && b5==b2)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn8.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn5.setBackground(Color.GREEN);
                btn2.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }
            else if(b8=="O" && b8==b7 && b8==b9)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn8.setBackground(Color.GREEN);
                btn7.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn9.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            count++;
            if (count==9)
            {reslvl.setText("Game is Draw...");
            JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();}
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if(btn9.getText()=="")
        {
            if(count%2==0)

            {
                btn9.setText("X");
                b9="X";
            }

            else

            {
                btn9.setText("O");
                b9="O";
            }

            if(b9=="X" && b9==b8 && b8==b7)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn8.setBackground(Color.CYAN);
                btn7.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn9.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();

            }
            else if(b9=="X" && b9==b5 && b5==b1)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn1.setBackground(Color.CYAN);
                btn5.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn9.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();

            }
            else if(b9=="X" && b9==b6 && b6==b3)
            {
                p1rec++;
                p1r= String.format("%d", p1rec);
                player1rec.setText(p1r);
                btn3.setBackground(Color.CYAN);
                btn6.setBackground(Color.CYAN);
                reslvl.setText("Player 1 Wins...");
                btn9.setBackground(Color.CYAN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();

            }
            else if(b9=="O" && b9==b8 && b8==b7)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn8.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn7.setBackground(Color.GREEN);
                btn9.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }
            else if(b9=="O" && b9==b5 && b5==b1)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn1.setBackground(Color.GREEN);
                btn5.setBackground(Color.GREEN);
                btn9.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }
            else if(b9=="O" && b9==b6 && b6==b3)
            {
                p2rec++;
                p2r= String.format("%d", p2rec);
                player2rec.setText(p2r);
                btn3.setBackground(Color.GREEN);
                reslvl.setText("Player 2 Wins...");
                btn6.setBackground(Color.GREEN);
                btn9.setBackground(Color.GREEN);
                 JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();
            }

            count++;
            if (count==9)
            {reslvl.setText("Game is Draw...");
            JOptionPane.showMessageDialog(null, reslvl);
                  btnreset.doClick();}
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        btnreset.doClick();
        name();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel player1name;
    private javax.swing.JLabel player1rec;
    private javax.swing.JLabel player2name;
    private javax.swing.JLabel player2rec;
    private javax.swing.JLabel reslvl;
    // End of variables declaration//GEN-END:variables
}
